export const REQUEST_AUTHENTICATION_TOKEN = 'REQUEST_AUTHENTICATION_TOKEN';
export const GET_AUTHENTICATION_TOKEN_SUCCESS = 'GET_AUTHENTICATION_TOKEN_SUCCESS';
export const GET_AUTHENTICATION_TOKEN_ERROR = 'GET_AUTHENTICATION_TOKEN_ERROR';
export const REFRESH_AUTHENTICATION_TOKEN_ERROR = 'REFRESH_AUTHENTICATION_TOKEN_ERROR';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';